version: "3.7"
services: 
  mysql:
    image: "mysql:latest"
    container_name: "mysql"
    ports: 
      - "3306:3306"
    volumes: 
      - "data:/var/lib/mysql"
      - "./conf.d:/etc/mysql/conf.d:ro"
    networks: 
      - "network"
    environment: 
      - "MYSQL_ROOT_PASSWORD=root"
    command: "--default-authentication-plugin=mysql_native_password"
networks: 
  network:
volumes: 
  data: 
    name: "study-node-orm-mysql-data"
