version: "3.9"
services:
  mysql:
    image: "mysql:latest"
    container_name: "mysql"
    privileged: true
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 256M
        reservations:
          memory: 100M
    ports:
      - "3306:3306"
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
      - "./sql/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql:ro"
      - "mysql_data:/var/lib/mysql"
    networks:
      - mysql_network
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    command: "--default-authentication-plugin=caching_sha2_password"
networks:
  mysql_network:
volumes:
  mysql_data:
