version: "3.9"
services:
  percona:
    image: percona/percona-server:8.0
    container_name: percona
    restart: always
    privileged: true
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./conf/percona.cnf:/etc/my.cnf.d/default.cnf:ro
      - ./sql/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql:ro
      - ./log:/var/log/mysql
      - percona_data:/var/lib/mysql
    networks:
      - percona_network
volumes:
  percona_data:
networks:
  percona_network:
